# Define Colors
import pygame

WHITE = pygame.Color('white')
BLACK = pygame.Color('black')
RED = pygame.Color('red')
GREEN = pygame.Color('green')
BLUE = pygame.Color('blue')
ORANGE = pygame.Color('orange')
BLUE = pygame.Color('blue')


COL_BOOKSTAND = BLACK
COL_SHELF = WHITE
COL_SELECTED = BLACK
COL_DONE = GREEN
COL_TIMER = BLUE

MENU_TEXT = BLACK
SELECTED_MENU_TEXT = BLUE
COL_PUZZLE_PROGRESS_BAR_OUTER = BLACK
COL_PUZZLE_PROGRESS_BAR_MIN = RED
COL_PUZZLE_PROGRESS_BAR_MID = ORANGE
COL_PUZZLE_PROGRESS_BAR_MAX = GREEN
COL_PUZZLE_PROGRESS_TEXT = RED